server:
  port: 8080

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver

#logging:
#  level:
#    root: DEBUG